### ISSUE TITLE
pbtetris nor scaling correctly on PB632 (Touch HD3)

### ISSUE THREAD

**Issue by neilswann80** [gottagofaster236/pbtetris#1]
![scr0002](https://github.com/gottagofaster236/pbtetris/assets/60895883/e5df9d67-d74c-4eed-b70e-a0fab71e5c40)

Any chance you can fix this?  It looks like it would play really nicely on my device, but not really playable as-is.

Thanks

**Comment by gottagofaster236** [comment]
> ![scr0002](https://github.com/gottagofaster236/pbtetris/assets/60895883/e5df9d67-d74c-4eed-b70e-a0fab71e5c40)
> 
> Any chance you can fix this?  It looks like it would play really nicely on my device, but not really playable as-is.
> 
> Thanks

Hello! Thanks for filling the issue.
Sorry, it's an old project, and I don't have much free time nowadays, so don't expect a fix from me soon. I can assist you with building the project if you would like to fix it yourself, though — you can write to me here or in Twitter dms 🙂

(The `CMakeLists.txt` contains some hardcoded pathnames, so it will require some tweaking. The code itself is from the times when I didn't know C++ well, so yeah 😅)

**Comment by neilswann80** [comment]
I shall try!  I have zero C++ experience, so will be an interesting journey.  Any idea as to where I should focus my attention?  What area of the code I should focus on?

**Comment by gottagofaster236** [comment]
@neilswann80 I can see you've made some progress on your side, congrats! I think I'll leave a link in README to your fork if/when you succeed in adapting it to your device.
Just one thing: please also upload the source code to your fork if you're publishing binary releases, as required by the GPL-3.0 license (that this repo has).

**Comment by neilswann80** [comment]
@gottagofaster236

Ok, will do.  I'll leave a message when I've pushed my latest changes over.

Was fun tinkering, I'm keen to try something from scratch now in C++.  

Here's what my modified version looks like:
![PBTetris_arrows](https://github.com/gottagofaster236/pbtetris/assets/60895883/2ce5c56a-7e25-4388-bcfa-76b018138677)

**Comment by neilswann80** [comment]
FYI - Updated the source files on my fork within the branch pB632

**Comment by gottagofaster236** [comment]
> FYI - Updated the source files on my fork within the branch pB632

@neilswann80
Thanks! Just in case, I've added the link to your fork in the README. Just one thing - could you also upload the changed images (i.e. of blocks and buttons) along with the source code? (Which is also required by the GPL-3 license). Thanks!

**Comment by neilswann80** [comment]
Images all updated now also.  The source code should already be the latest.  I think that's everything now?
